### PR TITLE
support for both python2 and python3

### PR DESCRIPTION
**Pull request by lambda-voodoo**
Propose modifications in order to use _pybgpstream python module with both python2 and python3.
My first python bindings to C, my first pull request.

### CODE REVIEW

**Comment by alistairking** [comment]
This looks really good, thanks.
I'll run it through some tests and then I think it can be merged.

**Comment by alistairking** [comment]
It seems that this generates some compiler warnings, but I'm going to merge this as it is and we can fix the warnings later.

**Comment by lambda-voodoo** [comment]
I'll have a look at it. Thank you.

**Comment by alistairking** [comment]
I've fixed the warnings (maybe they were errors?) in PR #15 
Thanks again for your contribution.

**Pull request merged**
